[package]
name = "rmeter"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
getopts = "0.2.21"
prost = "0.13.3"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros"]}
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
