# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_service/v1/v1.proto

require 'google/protobuf'


descriptor_data = "\n\x18test_service/v1/v1.proto\x12\x0ftest_service.v1\"\x0c\n\nCpuRequest\"\x1f\n\x0b\x43puResponse\x12\x10\n\x03\x66ib\x18\x01 \x01(\x05R\x03\x66ib\"\x0b\n\tDbRequest\"$\n\nDbResponse\x12\x16\n\x06result\x18\x01 \x01(\tR\x06result2\x8e\x01\n\x0bTestService\x12@\n\x03\x43pu\x12\x1b.test_service.v1.CpuRequest\x1a\x1c.test_service.v1.CpuResponse\x12=\n\x02\x44\x62\x12\x1a.test_service.v1.DbRequest\x1a\x1b.test_service.v1.DbResponseBw\n\x13\x63om.test_service.v1B\x07V1ProtoP\x01\xa2\x02\x03TXX\xaa\x02\x0eTestService.V1\xca\x02\x0eTestService\\V1\xe2\x02\x1aTestService\\V1\\GPBMetadata\xea\x02\x0fTestService::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module TestService
  module V1
    CpuRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test_service.v1.CpuRequest").msgclass
    CpuResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test_service.v1.CpuResponse").msgclass
    DbRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test_service.v1.DbRequest").msgclass
    DbResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("test_service.v1.DbResponse").msgclass
  end
end
