# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: test_service/v1/v1.proto for package 'TestService.V1'

require 'grpc'
require 'test_service/v1/v1_pb'

module TestService
  module V1
    module TestService
      class Service

        include ::GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'test_service.v1.TestService'

        rpc :Cpu, ::TestService::V1::CpuRequest, ::TestService::V1::CpuResponse
        rpc :Db, ::TestService::V1::DbRequest, ::TestService::V1::DbResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
